name: NameColor
version: 1.0.0
description: Utility Plugin
depend: [Vault]
author: Fahlur
main: me.Fahlur.NameColor.main

commands:
  namecolor:
      description: Name color command
      aliases: [nc]
      usage: /namecolor
